"""Remove perenual_id from species

Revision ID: ae85b61d56a4
Revises: 17a47775aaba
Create Date: 2025-07-07 13:14:40.591955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae85b61d56a4'
down_revision: Union[str, None] = '17a47775aaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'perenual_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('perenual_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
